apiVersion: v1
kind: Service
metadata:
  name: chatwithai
  labels:
    app: chatwithai
spec:
  selector:
    env: chatwithai-prod
  type: ClusterIP  # Changed from NodePort to ClusterIP
  ports:
    - port: 8101  # Service port
      targetPort: 8101  # Target port on the backend pods
